services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://engfaisalbhalli_db_user:3I4QmOtnYi1mmqql@sportstms.xqtjc1k.mongodb.net/authdb
      - JWT_SECRET=3KJ56TYJHJKTYRDFG5H6KJHGF5T6Y7U8I9O0P
      - NODE_ENV=development

  tournament-service:
    build: ./tournament-service
    ports:
      - "6000:6001"
    environment:
      - PORT=6001
      - MONGO_URI=mongodb+srv://engfaisalbhalli_db_user:3I4QmOtnYi1mmqql@sportstms.xqtjc1k.mongodb.net/tournamentdb
      - JWT_SECRET=3KJ56TYJHJKTYRDFG5H6KJHGF5T6Y7U8I9O0P
      - NODE_ENV=development

  team-service:
    build: ./team-service
    ports:
      - "7000:7001"
    environment:
      - PORT=7001
      - MONGO_URI=mongodb+srv://engfaisalbhalli_db_user:3I4QmOtnYi1mmqql@sportstms.xqtjc1k.mongodb.net/teamdb
      - JWT_SECRET=3KJ56TYJHJKTYRDFG5H6KJHGF5T6Y7U8I9O0P
      - NODE_ENV=development

  match-service:
    build: ./match-service
    ports:
      - "8000:8001"
    environment:
      - PORT=8001
      - MONGO_URI=mongodb+srv://engfaisalbhalli_db_user:3I4QmOtnYi1mmqql@sportstms.xqtjc1k.mongodb.net/matchdb
      - JWT_SECRET=3KJ56TYJHJKTYRDFG5H6KJHGF5T6Y7U8I9O0P
      - NODE_ENV=development

  standings-service:
    build: ./standings-service
    ports:
      - "9000:9001"
    environment:
      - PORT=9001
      - MONGO_URI=mongodb+srv://engfaisalbhalli_db_user:3I4QmOtnYi1mmqql@sportstms.xqtjc1k.mongodb.net/standingsdb
      - JWT_SECRET=3KJ56TYJHJKTYRDFG5H6KJHGF5T6Y7U8I9O0P
      - NODE_ENV=development

  announcement-service:
    build: ./announcement-service
    ports:
      - "10000:10001"
    environment:
      - PORT=10001
      - MONGO_URI=mongodb+srv://engfaisalbhalli_db_user:3I4QmOtnYi1mmqql@sportstms.xqtjc1k.mongodb.net/announcementdb
      - JWT_SECRET=3KJ56TYJHJKTYRDFG5H6KJHGF5T6Y7U8I9O0P
      - NODE_ENV=development