services:
  mongo_auth:
    image: mongo:latest
    container_name: mongo_auth_db
    restart: always
    volumes:
      - ./data/auth:/data/db
    ports:
      - "27017:27017"

  auth-service:
    build: ./auth-service
    container_name: auth_service
    depends_on:
      - mongo_auth
    ports:
      - "5000:5001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  mongo_tournament:
    image: mongo:latest
    container_name: mongo_tournament_db
    restart: always
    volumes:
      - ./data/tournament:/data/db
    ports:
      - "27018:27017"

  tournament-service:
    build: ./tournament-service
    container_name: tournament_service
    depends_on:
      - mongo_tournament
    ports:
      - "6000:6001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  mongo_team:
    image: mongo:latest
    container_name: mongo_team_db
    restart: always
    volumes:
      - ./data/team:/data/db
    ports:
      - "27019:27017"

  team-service:
    build: ./team-service
    container_name: team_service
    depends_on:
      - mongo_team
    ports:
      - "7000:7001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  mongo_match:
    image: mongo:latest
    container_name: mongo_match_db
    restart: always
    volumes:
      - ./data/match:/data/db
    ports:
      - "27020:27017"

  match-service:
    build: ./match-service
    container_name: match_service
    depends_on:
      - mongo_match
    ports:
      - "8000:8001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  mongo_standings:
    image: mongo:latest
    container_name: mongo_standings_db
    restart: always
    volumes:
      - ./data/standings:/data/db
    ports:
      - "27021:27017"

  standings-service:
    build: ./standings-service
    container_name: standings_service
    depends_on:
      - mongo_standings
    ports:
      - "9000:9001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  mongo_announcement:
    image: mongo:latest
    container_name: mongo_announcement_db
    restart: always
    volumes:
      - ./data/announcement:/data/db
    ports:
      - "27022:27017"

  announcement-service:
    build: ./announcement-service
    container_name: announcement_service
    depends_on:
      - mongo_announcement
    ports:
      - "10000:10001"
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
